### ISSUE TITLE
Wanted address not shown when using pywallet.py --dumpwallet

### ISSUE THREAD

**Issue by webwakko** [joric/pywallet#1]
Hi,
I'm using this py-script to recover my private key from my wallet, but when I run the dumpwallet command,  I see a lot of addresses passing by, except the one I need.
Strange thing is that when I open up the wallet, the wanted address is in the list of addresses in which I can receive coins.
Any idea why this one is not popping up and that dumplist?

**Comment by joric** [comment]
I guess you're asking for P2SH addresses (starting from 3, binary prefix 0x05). P2SH are 1-to-1 multisig adresses that use multisig script "OP_0 HASH160" instead of public key, so it's basically:

```addr = public_key_to_bc_address('\x00\x14' + hash_160(pub))```

According to bitcoin-core changelog the transition occured in 0.10.0 so everything with minversion >= 100000 is P2SH now.

Fixed in b5f83784

**Comment by schrodeo82** [comment]
HI I received an email from you, about an inquiry to get the private key for a bitcoin address that is a watch only address on blockchain. Please get back to me as I do not understand how to use the information you sent me. I'm new to this and haven't really been shown how to use pywallet to do so. So if you can please get back to me and give me a dumbed down step by step how to guide I would really appreciate it so I can retrieve my btc and at least transfer it to another wallet.

Thank You.
________________________________

**Comment by joric** [comment]
@schrodeo82 This thing only works with existing wallet.dat files from Bitcoin Core. It can't read damaged wallets and its only features are dumpwallet / dumpprivkey / importprivkey which are now part of Bitcoin Core. Please use Bitcoin Core instead.
