### ISSUE TITLE
pywallet to get LiteCoin privkey

### ISSUE THREAD

**Issue by Urbanoid** [joric/pywallet#10]
In 2015, my Desktop PC crashed while my Litecoin-QT wallet was open. I still have the wallet.dat file. I am not sure but I think the file is corrupted because I remember having moved the .dat file in a new LiteCoin-QT wallet (2 years ago) and an error message was saying something in the like of "corrupted file".  

Anyways. I've decided to try pywallet from joric.

Today, I installed Python 2.7 (Windows version) on a new laptop PC and I received an error message which is the following:

C:\Python27>python [pywallet.py](https://pywallet.py/) --dumpwallet

Traceback (most recent call last):

File "[pywallet.py](https://pywallet.py/)", line 1783, in <module> main()

File "[pywallet.py](https://pywallet.py/)", line 1740, in main

db_env = create_env(db_dir)

File "[pywallet.py](https://pywallet.py/)", line 1180, in create_env

r = db_env.open(db_dir, (DB_CREATE|DB_INIT_LOCK|DB_INIT_LOG|DB_INIT_MPOOL|DB_INIT_TXN|DB_THREAD|DB_RECOVER))

bsddb.db.DBNoSuchFileError: (2, 'No such file or directory -- C:\\Users\\15146\\AppData\\Roaming\\Bitcoin\\__db.001: No such file or directory')

Can someone here tell me what is the problem as I am not a coder nor a programmer.

![dumpwallet Litecoin-QT](https://user-images.githubusercontent.com/19229166/175118015-cc4ab1ec-e51b-4696-8f8f-8c111e87cab0.JPG)

**Comment by Urbanoid** [comment]
Then I tried this (suggested by a Reddit member on r/Litecoin)...


python pywallet.py --dumpwallet --datadir=C:\Python27

I am now getting this error message...

C:\Python27>python pywallet.py --dumpwallet --datadir=C:\Python27

ERROR:root:Couldn't open wallet.dat/main. Try quitting Bitcoin and running this again.


I am not running "Bitcoin". I don't know what this is about.

Can someone here tell me if a private key from a corrupted file can be recovered with the pywallet method?

**Comment by GhegethDev** [comment]
@Urbanoid Talk to Litecoin Support on the [Live support page](https://litecoin-community.net/litecoin/projects.html) so that your issue can be looked into.
