### ISSUE TITLE
Output File Content

### ISSUE THREAD

**Issue by mfread** [joric/pywallet#5]
Hi. The --dumpwallet param provided me output, but I don't see any documentation anywhere to describe the output content.

Here's a few lines of my output ...

`{
    "bestblock": "c3a386b33958520a58e26c750a7177e6d6c6d40a7d88a736c95fde33bd49531c", 
    "defaultkey": "16G3gj5B6LQveDmQypYHrsTbghvVfSp6jn", 
    "keys": [
        {
            "addr": "1NNKB8fF6H5nTqmFFp7Ait9b7zZdBfkQff", 
            "reserve": 1, 
            "sec": "L2ywxvQz7uAbhuzUAixd9uHwY3fKaajw22dCr2QVrFm5Knp2wxye"
        }, 
        {
            "addr": "1H8xxRLE6o5RPA8TNfYCj7FjGAyzMkR1rv", 
            "reserve": 1, 
            "sec": "KxFgAhRx9dtgsQBMofvz2zMXizrx9AUNX68PCwTDXuKL449jYemb"
        },
---cut---
    ], 
    "minversion": 60000, 
    "mkey": {
        "crypted_key": "4a5506d6446f9677f878ea274095c86ec9232adc3cb0dd649fdeda7704245172d334002ef4ea5f9071d832c432106825", 
        "nDerivationMethod": 0, 
        "nDeriveIterations": 51842, 
        "nID": 1, 
        "salt": "80d864ca93a67343", 
        "vchOtherDerivationParameters": ""
    }, 
    "orderposnext": "unsupported", 
    "settings": {
        "addrIncoming": "0.0.0.0:0"
    }, 
    "tx": "unsupported", 
    "version": 1060000
}
`

It's a dump of my Doge wallet.dat

Doge Public addresses start with 'D' ... none of the addresses in the output start with 'D" - they all start with '1' (which from memory is a Bitcoin public address).

I also don't see my Private key either.

Am I doing something wrong?

Cheers,
Mark

**Comment by arranka** [comment]
scam

**Comment by joric** [comment]
This project is super old and it doesn't support doge, you need to change addrtype to whatever the hell doge is, considering they even suport bitcoin address scheme that I'm not sure they do. Private key is "sec" but it's in bitcoin encoding as well. Cheers.
